export const seoKeywords = [
  'DNS lookup',
  'DNS lookup tool',
  'DNS lookup online',
  'DNS checker',
  'DNS checker online',
  'DNS records',
  'DNS record lookup',
  'DNS records lookup',
  'check DNS records',
  'DNS records checker',
  'domain DNS lookup',
  'domain DNS checker',
  'DNS query',
  'DNS propagation',
  'DNS propagation checker',
  'DNS propagation lookup',
  'global DNS checker',
  'check DNS propagation',
  'DNS resolver',
  'nameserver lookup',
  'check nameservers',
  'nameserver checker',
  'NS record checker',
  'nslookup',
  'online nslookup',
  'dig DNS',
  'dig online',
  'A record lookup',
  'AAAA record lookup',
  'CNAME lookup',
  'MX lookup',
  'MX record lookup',
  'NS lookup',
  'TXT lookup',
  'TXT record lookup',
  'SOA lookup',
  'CAA lookup',
  'PTR lookup',
  'PTR record lookup',
  'SPF check',
  'SPF record lookup',
  'DMARC check',
  'DKIM lookup',
  'reverse DNS lookup',
  'reverse DNS search',
  'rDNS lookup',
  'IP to hostname lookup',
  'reverse IP lookup',
  'reverse IP domain lookup',
  'same IP domains',
  'same IP website lookup',
  'find domains on IP',
  'subdomain finder',
  'subdomain finder online',
  'subdomain discovery',
  'find subdomains',
  'subdomain lookup',
  'reverse NS lookup',
  'reverse MX lookup',
  'shared nameservers',
  'mail infrastructure lookup',
  'DNSSEC checker',
  'DNS API',
  'public DNS API',
  'domain intelligence',
  'infrastructure discovery',
  '域名解析',
  'DNS查询',
  'DNS查询工具',
  'DNS在线查询',
  'DNS查找',
  'DNS记录查询',
  'DNS记录查询工具',
  'DNS记录检测',
  'DNS检测',
  'DNS解析查询',
  'DNS解析检测',
  'DNS生效检测',
  '全球DNS检测',
  '域名DNS查询',
  '域名DNS检测',
  '域名NS查询',
  'Nameserver查询',
  '域名服务器查询',
  'DNS传播检测',
  'nslookup查询',
  '在线nslookup',
  'dig查询',
  '在线dig',
  'A记录查询',
  'AAAA记录查询',
  'CNAME查询',
  'MX记录查询',
  'NS记录查询',
  'TXT记录查询',
  'SOA记录查询',
  'CAA记录查询',
  'PTR查询',
  'PTR记录查询',
  'SPF查询',
  'DMARC查询',
  'DKIM查询',
  '反向DNS查询',
  '反向DNS搜索',
  'rDNS查询',
  'IP反查域名',
  '反向IP查询',
  '同IP域名查询',
  '子域名查询',
  '子域名发现',
  '子域名查询工具',
  '反向NS查询',
  '反向MX查询',
  'DNSSEC检测',
  'DNS API接口',
  '域名情报',
  '基础设施发现',
]

export function seoMeta({
  title,
  description,
  keywords = [],
}: {
  title: string
  description: string
  keywords?: string[]
}) {
  return [
    { title },
    { name: 'description', content: description },
    { name: 'keywords', content: [...keywords, ...seoKeywords].join(', ') },
    { property: 'og:title', content: title },
    { property: 'og:description', content: description },
    { property: 'og:type', content: 'website' },
    { property: 'og:site_name', content: 'DNS.NF' },
    { name: 'twitter:card', content: 'summary' },
    { name: 'twitter:title', content: title },
    { name: 'twitter:description', content: description },
  ]
}
