export const seoKeywords = [
  'DNS lookup',
  'DNS checker',
  'DNS records',
  'check DNS records',
  'DNS records checker',
  'DNS query',
  'DNS propagation',
  'DNS resolver',
  'nameserver lookup',
  'check nameservers',
  'nameserver checker',
  'NS record checker',
  'nslookup',
  'dig DNS',
  'A record lookup',
  'AAAA record lookup',
  'CNAME lookup',
  'MX lookup',
  'NS lookup',
  'TXT lookup',
  'SOA lookup',
  'CAA lookup',
  'PTR lookup',
  'SPF check',
  'DMARC check',
  'reverse DNS lookup',
  'rDNS lookup',
  'reverse IP lookup',
  'subdomain finder',
  'subdomain discovery',
  'reverse NS lookup',
  'reverse MX lookup',
  'shared nameservers',
  'mail infrastructure lookup',
  'DNSSEC checker',
  'DNS API',
  'public DNS API',
  'domain intelligence',
  'infrastructure discovery',
  '域名解析',
  'DNS查询',
  'DNS查找',
  'DNS记录查询',
  'DNS记录检测',
  'DNS检测',
  'DNS解析查询',
  '域名DNS查询',
  '域名NS查询',
  'Nameserver查询',
  'DNS传播检测',
  'nslookup查询',
  'dig查询',
  'A记录查询',
  'AAAA记录查询',
  'CNAME查询',
  'MX记录查询',
  'NS记录查询',
  'TXT记录查询',
  'SOA记录查询',
  'CAA记录查询',
  'PTR查询',
  'SPF查询',
  'DMARC查询',
  '反向DNS查询',
  'rDNS查询',
  '反向IP查询',
  '子域名查询',
  '反向NS查询',
  '反向MX查询',
  'DNSSEC检测',
  'DNS API接口',
  '域名情报',
  '基础设施发现',
]

export function seoMeta({
  title,
  description,
  keywords = [],
}: {
  title: string
  description: string
  keywords?: string[]
}) {
  return [
    { title },
    { name: 'description', content: description },
    { name: 'keywords', content: [...keywords, ...seoKeywords].join(', ') },
    { property: 'og:title', content: title },
    { property: 'og:description', content: description },
    { property: 'og:type', content: 'website' },
    { property: 'og:site_name', content: 'DNS.NF' },
    { name: 'twitter:card', content: 'summary' },
    { name: 'twitter:title', content: title },
    { name: 'twitter:description', content: description },
  ]
}
