CREATE TABLE IF NOT EXISTS traffic_stats_baseline (
  key TEXT PRIMARY KEY,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  total_requests BIGINT NOT NULL DEFAULT 0,
  seeded_from_30d BOOLEAN NOT NULL DEFAULT FALSE
);
