/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubdomainsRouteImport } from './routes/subdomains'
import { Route as SharedNsRouteImport } from './routes/shared-ns'
import { Route as ReverseNsRouteImport } from './routes/reverse-ns'
import { Route as ReverseMxRouteImport } from './routes/reverse-mx'
import { Route as ReverseIpRouteImport } from './routes/reverse-ip'
import { Route as RdnsRouteImport } from './routes/rdns'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DnssecRouteImport } from './routes/dnssec'
import { Route as DnsLookupRouteImport } from './routes/dns-lookup'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as LookupDomainRouteImport } from './routes/lookup.$domain'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SubdomainsRoute = SubdomainsRouteImport.update({
  id: '/subdomains',
  path: '/subdomains',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedNsRoute = SharedNsRouteImport.update({
  id: '/shared-ns',
  path: '/shared-ns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReverseNsRoute = ReverseNsRouteImport.update({
  id: '/reverse-ns',
  path: '/reverse-ns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReverseMxRoute = ReverseMxRouteImport.update({
  id: '/reverse-mx',
  path: '/reverse-mx',
  getParentRoute: () => rootRouteImport,
} as any)
const ReverseIpRoute = ReverseIpRouteImport.update({
  id: '/reverse-ip',
  path: '/reverse-ip',
  getParentRoute: () => rootRouteImport,
} as any)
const RdnsRoute = RdnsRouteImport.update({
  id: '/rdns',
  path: '/rdns',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DnssecRoute = DnssecRouteImport.update({
  id: '/dnssec',
  path: '/dnssec',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsLookupRoute = DnsLookupRouteImport.update({
  id: '/dns-lookup',
  path: '/dns-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const LookupDomainRoute = LookupDomainRouteImport.update({
  id: '/lookup/$domain',
  path: '/lookup/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/blog': typeof BlogRouteWithChildren
  '/dns-lookup': typeof DnsLookupRoute
  '/dnssec': typeof DnssecRoute
  '/docs': typeof DocsRoute
  '/rdns': typeof RdnsRoute
  '/reverse-ip': typeof ReverseIpRoute
  '/reverse-mx': typeof ReverseMxRoute
  '/reverse-ns': typeof ReverseNsRoute
  '/shared-ns': typeof SharedNsRoute
  '/subdomains': typeof SubdomainsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/lookup/$domain': typeof LookupDomainRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/dns-lookup': typeof DnsLookupRoute
  '/dnssec': typeof DnssecRoute
  '/docs': typeof DocsRoute
  '/rdns': typeof RdnsRoute
  '/reverse-ip': typeof ReverseIpRoute
  '/reverse-mx': typeof ReverseMxRoute
  '/reverse-ns': typeof ReverseNsRoute
  '/shared-ns': typeof SharedNsRoute
  '/subdomains': typeof SubdomainsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/lookup/$domain': typeof LookupDomainRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/blog': typeof BlogRouteWithChildren
  '/dns-lookup': typeof DnsLookupRoute
  '/dnssec': typeof DnssecRoute
  '/docs': typeof DocsRoute
  '/rdns': typeof RdnsRoute
  '/reverse-ip': typeof ReverseIpRoute
  '/reverse-mx': typeof ReverseMxRoute
  '/reverse-ns': typeof ReverseNsRoute
  '/shared-ns': typeof SharedNsRoute
  '/subdomains': typeof SubdomainsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/lookup/$domain': typeof LookupDomainRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/blog'
    | '/dns-lookup'
    | '/dnssec'
    | '/docs'
    | '/rdns'
    | '/reverse-ip'
    | '/reverse-mx'
    | '/reverse-ns'
    | '/shared-ns'
    | '/subdomains'
    | '/blog/$slug'
    | '/lookup/$domain'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/dns-lookup'
    | '/dnssec'
    | '/docs'
    | '/rdns'
    | '/reverse-ip'
    | '/reverse-mx'
    | '/reverse-ns'
    | '/shared-ns'
    | '/subdomains'
    | '/blog/$slug'
    | '/lookup/$domain'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/blog'
    | '/dns-lookup'
    | '/dnssec'
    | '/docs'
    | '/rdns'
    | '/reverse-ip'
    | '/reverse-mx'
    | '/reverse-ns'
    | '/shared-ns'
    | '/subdomains'
    | '/blog/$slug'
    | '/lookup/$domain'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  BlogRoute: typeof BlogRouteWithChildren
  DnsLookupRoute: typeof DnsLookupRoute
  DnssecRoute: typeof DnssecRoute
  DocsRoute: typeof DocsRoute
  RdnsRoute: typeof RdnsRoute
  ReverseIpRoute: typeof ReverseIpRoute
  ReverseMxRoute: typeof ReverseMxRoute
  ReverseNsRoute: typeof ReverseNsRoute
  SharedNsRoute: typeof SharedNsRoute
  SubdomainsRoute: typeof SubdomainsRoute
  LookupDomainRoute: typeof LookupDomainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subdomains': {
      id: '/subdomains'
      path: '/subdomains'
      fullPath: '/subdomains'
      preLoaderRoute: typeof SubdomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-ns': {
      id: '/shared-ns'
      path: '/shared-ns'
      fullPath: '/shared-ns'
      preLoaderRoute: typeof SharedNsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reverse-ns': {
      id: '/reverse-ns'
      path: '/reverse-ns'
      fullPath: '/reverse-ns'
      preLoaderRoute: typeof ReverseNsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reverse-mx': {
      id: '/reverse-mx'
      path: '/reverse-mx'
      fullPath: '/reverse-mx'
      preLoaderRoute: typeof ReverseMxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reverse-ip': {
      id: '/reverse-ip'
      path: '/reverse-ip'
      fullPath: '/reverse-ip'
      preLoaderRoute: typeof ReverseIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rdns': {
      id: '/rdns'
      path: '/rdns'
      fullPath: '/rdns'
      preLoaderRoute: typeof RdnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dnssec': {
      id: '/dnssec'
      path: '/dnssec'
      fullPath: '/dnssec'
      preLoaderRoute: typeof DnssecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns-lookup': {
      id: '/dns-lookup'
      path: '/dns-lookup'
      fullPath: '/dns-lookup'
      preLoaderRoute: typeof DnsLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/lookup/$domain': {
      id: '/lookup/$domain'
      path: '/lookup/$domain'
      fullPath: '/lookup/$domain'
      preLoaderRoute: typeof LookupDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  BlogRoute: BlogRouteWithChildren,
  DnsLookupRoute: DnsLookupRoute,
  DnssecRoute: DnssecRoute,
  DocsRoute: DocsRoute,
  RdnsRoute: RdnsRoute,
  ReverseIpRoute: ReverseIpRoute,
  ReverseMxRoute: ReverseMxRoute,
  ReverseNsRoute: ReverseNsRoute,
  SharedNsRoute: SharedNsRoute,
  SubdomainsRoute: SubdomainsRoute,
  LookupDomainRoute: LookupDomainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
